version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ggemre"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      cron: "34 8 */5 * *"
    assignees:
      - "ggemre"
