name: "Build and deploy"
on:
  push:
    branches: [main]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      pkgs_changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v6

      - id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            changed:
              - 'pkgs/**/*.nix'

  tests:
    needs: detect
    if: needs.detect.outputs.pkgs_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build nix packages
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run nixpkgs#nix-fast-build -- \
              --no-nom --skip-cached -cachix-cache ggemre
