name: "Cache warmer"
on:
  push:
    branches: [ main ]
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v14
        with:
          name: ggemre
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build all packages
        run: |
          files=$(nix flake show --json | jq -r '.packages."x86_64-linux" | keys[]')
          attrs=$(echo "$files" | sort -u | sed 's/^/.#/' | paste -sd ' ')
          echo "Building attrs: $attrs"

          nix build $attrs

      # - name: Push to cache
      #   run: |
      #     paths=$(nix path-info ./result*)
      #     echo "Pushing $paths"
      #     nix run nixpkgs#cachix -- push ggemre $paths
      #   env:
      #     CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

