name: "Build and deploy"
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Get changes to pkgs
        id: filter
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          filters: |
            pkgs:
              - added|modified: 'pkgs/**/*.nix'

      - name: Setup cachix
        uses: cachix/cachix-action@v17
        with:
          name: ggemre
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: >
            (-source$ | nixpkgs\.tar\.gz$)

      - name: Build packages
        run: |
          files="${{ steps.filter.outputs.pkgs_files }}"

          if [ -z "$files" ]; then
            echo "No package changes"
            exit 0
          fi

          attrs=$(for f in $files; do
            basename "$(dirname "$f")"
          done | sort -u | sed 's/^/.#/' | paste -sd ' ')

          echo "Building attrs: $attrs"

          nix build $attrs
