name: "Run checks on builds"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # detect:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     nix_changed: ${{ steps.filter.outputs.changed }}
  #   steps:
  #     - uses: actions/checkout@v6

  #     - id: filter
  #       uses: dorny/paths-filter@v4
  #       with:
  #         filters: |
  #           changed:
  #             - '**/*.nix'

  tests:
    # needs: detect
    # if: needs.detect.outputs.nix_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: "${{ env.nix_path }}"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # - name: Check formatting
      #   run: nix fmt -- . --check

      - name: Build nix packages
        run: |
          nix run nixpkgs#nix-fast-build -- --no-nom --skip-cached
