name: "Run checks on builds"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      nix_changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed:
              - '**/*.nix'

  tests:
    needs: detect
    if: needs.detect.outputs.nix_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: "${{ env.nix_path }}"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: nix fmt -- . --check

      - name: Get changed files
        id: changed_pkgs
        uses: tj-actions/changed-files@v47
        with:
          since_last_remote_commit: true 
          files: |
            pkgs/**/*.nix

      - name: Build packages
        run: |
          CHANGED_PKGS=$(
            printf "%s\n" "pkgs/alejandra-spaced/default.nix pkgs/mangowm-wlonly/wlroots.nix" \
            | tr ' ' '\n' \
            | awk -F/ '/^pkgs\// {print $2}'
          )

          echo "Changed packages: $CHANGED_PKGS"

          if [ -z "$CHANGED_PKGS" ]; then
            echo "No package changes, skipping"
            exit 0
          fi

          for pkg in $CHANGED_PKGS; do
            echo "Building $pkg"
            nix build .#packages.x86_64-linux."$pkg" \
              --override-input nixpkgs github:NixOS/nixpkgs/nixos-unstable
          done
