# Test the SD image arm builder on demand
name: "Benchmark image"
on:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        image: [ sd-installer ]

    concurrency:
      group: benchmark-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build image
        run: |
          nix build \
            .#images.${{ matrix.image }}.config.system.build.sdImage

      - name: Debug info
        run: |
          ls -R result

